### PR TITLE
Prevent the error when explicitly specifying default buf gen temlate file path

### PR DESCRIPTION
**Pull request by un1024**
Backgroud: I encountered the following error.
```
Buf gen template file specified in the project directory as well as with templateFileLocation; pick one.
```
But I have just one template file `{rootDir}/buf.gen.yaml`.
I didn't understand the reason for the error until I read the source code.

I think it's natural to want to specify the file path explicitly.
Therefore how about making this trivial fix to prevent confusion?

Thanks.

### CODE REVIEW

**Review by drice-buf — COMMENTED** [review]
LGTM with comments + rebase

**Comment by drice-buf** [comment]
@un1024 Please let me know in the next day or so if you still want to be involved with this PR, otherwise I will go ahead and push my change to the branch and get the PR merged.

**Comment by un1024** [comment]
@drice-buf Sorry, I've forgotten this Pull Request and am late... 🙇  I have fixed and pushed for your comments. 
Ofcourse I am fine with you to change it there.(If necessary, you can discard my pull request if you like, too.)
Thank you for your time.

**Review by drice-buf — APPROVED** [review]

**Comment by drice-buf** [comment]
@un1024 thanks for the PR and for bringing it up to date quickly.

**Pull request merged**
